# Generated by Django 5.2.5 on 2025-09-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_sop_audio_url_product_sop_text'),
    ]

    operations = [
    ]
