# Generated by Django 5.2.5 on 2025-10-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_normalize_product_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'name'), name='uq_active_variant_name_per_product'),
        ),
    ]
