# Generated by Django 5.2.5 on 2025-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodifiergroup',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
