# Generated by Django 5.2.5 on 2025-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productmodifiergroup_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodifiergroup',
            name='show_group',
            field=models.BooleanField(default=True),
        ),
    ]
