# Generated by Django 5.2.5 on 2025-12-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productmodifiergroup_show_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodifiergroup',
            name='required_variant',
            field=models.ForeignKey(blank=True, help_text='Only show this modifier group if this variant is selected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant'),
        ),
    ]
