# Generated by Django 5.2.5 on 2026-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productmodifiergroup_required_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieroption',
            name='multi_click',
            field=models.BooleanField(default=False),
        ),
    ]
