# Generated by Django 5.2.5 on 2026-04-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_modifieroption_multi_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodifiergroup',
            name='required_option',
            field=models.ForeignKey(blank=True, help_text='Only show this modifier group if this modifier option is selected (sub-modifier)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.modifieroption'),
        ),
    ]
