# Generated by Django 5.2.5 on 2026-04-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productmodifiergroup_required_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodifiergroup',
            name='required_option',
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='required_options',
            field=models.ManyToManyField(blank=True, help_text='Only show this modifier group if ANY of these modifier options are selected (sub-modifier)', to='catalog.modifieroption'),
        ),
    ]
