# Generated by Django 5.2.5 on 2025-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_credit_given_order_credit_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDayCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('seq', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
