# Generated by Django 5.2.5 on 2025-10-08 01:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderdaycounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('order', 'Order'), ('item', 'Item')], max_length=10)),
                ('mode', models.CharField(choices=[('qty', 'By Quantity'), ('amount', 'By Amount'), ('percent', 'By Percent')], max_length=10)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['station', 'status'], name='orders_kitc_station_9d0dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenticket',
            index=models.Index(fields=['created_at'], name='orders_kitc_created_44cde2_idx'),
        ),
        migrations.AddField(
            model_name='ordercomp',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordercomp',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='ordercomp',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordercomp',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_comps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ordercomp',
            index=models.Index(fields=['order', 'voided_at'], name='orders_orde_order_i_07aed1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercomp',
            index=models.Index(fields=['item'], name='orders_orde_item_id_cfbe46_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercomp',
            index=models.Index(fields=['created_at'], name='orders_orde_created_575580_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordercomp',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('scope', 'item')), models.Q(('item__isnull', True), ('scope', 'order')), _connector='OR'), name='comp_item_required_for_item_scope'),
        ),
    ]
