# Generated by Django 5.2.5 on 2025-10-09 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordercomp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='tab_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='tab_opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid_by'], name='orders_orde_paid_by_98d4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tab_opened_by'], name='orders_orde_tab_ope_b398c4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tab_closed_by'], name='orders_orde_tab_clo_174a97_idx'),
        ),
    ]
