# Generated by Django 5.2.5 on 2025-10-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_cashsession_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name_snapshot',
            field=models.CharField(default='', max_length=50),
        ),
    ]
