# orders/migrations/0014_backfill_item_name_snapshots.py
# Generated by Django 5.2.5 on 2025-10-10 12:20

from django.db import migrations
from django.db.models import Q


def forwards(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")

    # Any items missing either snapshot
    qs = OrderItem.objects.filter(
        Q(product_name_snapshot__isnull=True) | Q(product_name_snapshot="") |
        Q(variant_name_snapshot__isnull=True) | Q(variant_name_snapshot="")
    ).select_related("product", "variant")

    BATCH = 1000
    ids = list(qs.values_list("id", flat=True))

    for i in range(0, len(ids), BATCH):
        chunk_ids = ids[i:i + BATCH]
        items = (
            OrderItem.objects
            .filter(id__in=chunk_ids)
            .select_related("product", "variant")
        )

        to_update = []
        for oi in items:
            # Read current names (safe even if product/variant later archived)
            p_name = getattr(oi.product, "name", "") if oi.product_id else ""
            v_name = getattr(oi.variant, "name", "") if oi.variant_id else ""

            if (oi.product_name_snapshot or "") != p_name or (oi.variant_name_snapshot or "") != v_name:
                oi.product_name_snapshot = p_name
                oi.variant_name_snapshot = v_name
                to_update.append(oi)

        if to_update:
            OrderItem.objects.bulk_update(
                to_update,
                ["product_name_snapshot", "variant_name_snapshot"],
                batch_size=BATCH,
            )


def backwards(apps, schema_editor):
    # No-op: we don't want to erase snapshots.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_orderitem_product_alter_orderitem_variant_and_more"),
        # You can add a catalog dependency if you want strict ordering, but it's not required:
        # ("catalog", "<latest_catalog_migration_name_here>"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
