# Generated by Django 5.2.5 on 2025-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cashsession_backfilled_at_cashsession_backfilled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='base_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
