# Generated by Django 5.2.5 on 2025-11-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_base_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'Thai QR'), ('transfer', 'Bank Transfer'), ('other', 'Other'), ('pending', 'Pending / Pay Later')], default='cash', max_length=16),
        ),
    ]
