# Generated by Django 5.2.5 on 2025-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodifier',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
