# Generated by Django 5.2.5 on 2025-11-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_orderitemmodifier_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenticket',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.orderitem'),
        ),
    ]
