# Generated by Django 5.2.5 on 2025-11-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_kitchenticket_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenticket',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='queued', max_length=12),
        ),
    ]
